---
# file: tasks/use-yum.yml
#
# Configure Node.js from YUM repository.
#
# @see https://github.com/nodesource/distributions
#

- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present

- name: install tools for compiling native addons from npm
  yum: name={{ item }} state=present
  with_items:
    - gcc-c++
    - make
  when: nodejs_compile



- block:

    - name: add NodeSource repository for Node.js 6.0
      yum: name=https://rpm.nodesource.com/pub_6.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm state=present
      when: (nodejs_version|string) | match('^6.*$')

    - name: add NodeSource repository for Node.js 5.0
      yum: name=https://rpm.nodesource.com/pub_5.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm state=present
      when: (nodejs_version|string) | match('^5.*$')

    - name: add NodeSource repository for Node.js 4.0
      yum: name=https://rpm.nodesource.com/pub_4.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm state=present
      when: (nodejs_version|string) | match('^4.*$')

    - name: add NodeSource repository for Node.js 0.xx
      yum: name=https://rpm.nodesource.com/pub/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm state=present
      when: (nodejs_version|string) | match('^0.*$')

    - name: install Node.js with specific version
      yum: name="nodejs-{{ nodejs_version }}*"  update_cache=yes  state=present

  when: nodejs_version is defined


- fail: msg="io.js not supported for CentOS/RHEL."
  when: iojs_version is defined
