- name: generate locale
  locale_gen: >-
    name={{ base_locale }}
    state=present
  ignore_errors: true

- name: update apt configuration
  template: >-
    src=sources.list
    dest=/etc/apt/sources.list

- name: set apt proxy
  template: >-
    src=99proxy
    dest=/etc/apt/apt.conf.d/99proxy
    mode=0644
  when: mirror_apt_url is defined

- name: update apt cache
  apt: >-
    update_cache=yes

- name: install apt pre-packages
  apt: >-
    pkg={{ item }}
  with_items: base_apt_pre_pkgs

- name: add apt extra repositories
  apt_repository: >-
    repo={{ item }}
  with_items: base_apt_extra_repositories

- name: install apt packages
  apt: >-
    pkg={{ item }}
  with_items: base_apt_pkgs

- name: configure unattended-upgrades
  template: >-
    src=50unattended-upgrades
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    mode=0644

- name: setup periodic apt upgrades
  template: >-
    src=10periodic
    dest=/etc/apt/apt.conf.d/10periodic
    mode=0644
