# - name: Set timezone
#   command: >
#     sudo timedatectl set-timezone {{ base_timezone }}
#   tags:
#     - timezone

- name: generate locale
  locale_gen: >-
    name={{ base_locale }}
    state=present
  ignore_errors: true

- name: update apt cache
  apt: >-
    update_cache=yes

- name: install apt pre-packages
  apt: >-
    pkg={{ item }}
  with_items: base_apt_pre_pkgs

- name: add apt extra repositories
  apt_repository: >-
    repo={{ item }}
  with_items: base_apt_extra_repositories

- name: install apt packages
  apt: >-
    pkg={{ item }}
  with_items: base_apt_pkgs

- name: configure unattended-upgrades
  template: >-
    src=50unattended-upgrades
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    mode=0644

- name: setup periodic apt upgrades
  template: >-
    src=10periodic
    dest=/etc/apt/apt.conf.d/10periodic
    mode=0644

- name: add permissions to ssh auth sock path
  command: >-
    chmod -R 0777 {{ ansible_env.SSH_AUTH_SOCK | dirname }}
  ignore_errors: true
  notify:
    - revert ssh_auth_sock permissions
  when: ansible_env.SSH_AUTH_SOCK is defined
  tags:
    - deploy
