- name: add apt extra repositories
  apt_repository: >-
    repo={{ item }}
  with_items: '{{ base_nodejs_apt_extra_repositories }}'

- name: install apt packages
  apt: >-
    pkg={{ item }}
  with_items: '{{ base_nodejs_apt_pkgs }}'

- name: install global npm dependencies
  npm: >-
    name={{ item.name }}
    version={{ item.version | default('latest') }}
    global=yes
  register: gnpminstall
  with_items: '{{ base_nodejs_npm_pkgs }}'
  tags:
    - deploy
